import {updateFilm} from './update-film';


describe(`updateFilm work correctly`, () => {
  it(`The value of 13 minutes should return the "13m" string`, () => {
    const mockFilms = [{
      backgroundColor: `#A6B7AC`,
      backgroundImage: `https://htmlacademy-react-2.appspot.com/wtw/static/film/background/gangs_of_new_york.jpg`,
      description: `In 1862, Amsterdam Vallon returns to the Five Points area of New York City seeking revenge against Bill the Butcher, his father's killer.`,
      director: `Martin Scorsese`,
      genre: `Crime`,
      id: 1,
      isFavorite: false,
      name: `Gangs of new york`,
      posterImage: `https://htmlacademy-react-2.appspot.com/wtw/static/film/poster/Gangs_of_New_York_Poster.jpg`,
      previewImage: `https://htmlacademy-react-2.appspot.com/wtw/static/film/preview/gangs_of_new_york.jpg`,
      previewVideoLink: `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
      rating: 8.8,
      released: 2002,
      runTime: 167,
      scoresCount: 370881,
      starring: [`Leonardo DiCaprio`, `Cameron Diaz`, `Daniel Day-Lewis`],
      videoLink: `http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4`,
    }, {
      backgroundColor: `#9B7E61`,
      backgroundImage: `https://htmlacademy-react-2.appspot.com/wtw/static/film/background/War_of_the_Worlds.jpg`,
      description: `As Earth is invaded by alien tripod fighting machines, one family fights for survival.`,
      director: `Steven Spielberg`,
      genre: `Adventure`,
      id: 2,
      isFavorite: false,
      name: `War of the Worlds`,
      posterImage: `https://htmlacademy-react-2.appspot.com/wtw/static/film/poster/War_of_the_Worlds.jpg`,
      previewImage: `https://htmlacademy-react-2.appspot.com/wtw/static/film/preview/war-of-the-worlds.jpg`,
      previewVideoLink: `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
      rating: 9.3,
      released: 2005,
      runTime: 116,
      scoresCount: 386834,
      starring: [`Tom Cruise`, `Dakota Fanning`, `Tim Robbins`],
      videoLink: `http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4`,
    }];

    const mockUpdateFilm = {
      backgroundColor: `#9B7E61`,
      backgroundImage: `https://htmlacademy-react-2.appspot.com/wtw/static/film/background/War_of_the_Worlds.jpg`,
      description: `As Earth is invaded by alien tripod fighting machines, one family fights for survival.`,
      director: `Steven Spielberg`,
      genre: `Adventure`,
      id: 2,
      isFavorite: true,
      name: `War of the Worlds`,
      posterImage: `https://htmlacademy-react-2.appspot.com/wtw/static/film/poster/War_of_the_Worlds.jpg`,
      previewImage: `https://htmlacademy-react-2.appspot.com/wtw/static/film/preview/war-of-the-worlds.jpg`,
      previewVideoLink: `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
      rating: 9.3,
      released: 2005,
      runTime: 116,
      scoresCount: 386834,
      starring: [`Tom Cruise`, `Dakota Fanning`, `Tim Robbins`],
      videoLink: `http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4`,
    };

    const updatedFilms = updateFilm(mockFilms, mockUpdateFilm);
    expect(updatedFilms).toEqual([{
      backgroundColor: `#A6B7AC`,
      backgroundImage: `https://htmlacademy-react-2.appspot.com/wtw/static/film/background/gangs_of_new_york.jpg`,
      description: `In 1862, Amsterdam Vallon returns to the Five Points area of New York City seeking revenge against Bill the Butcher, his father's killer.`,
      director: `Martin Scorsese`,
      genre: `Crime`,
      id: 1,
      isFavorite: false,
      name: `Gangs of new york`,
      posterImage: `https://htmlacademy-react-2.appspot.com/wtw/static/film/poster/Gangs_of_New_York_Poster.jpg`,
      previewImage: `https://htmlacademy-react-2.appspot.com/wtw/static/film/preview/gangs_of_new_york.jpg`,
      previewVideoLink: `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
      rating: 8.8,
      released: 2002,
      runTime: 167,
      scoresCount: 370881,
      starring: [`Leonardo DiCaprio`, `Cameron Diaz`, `Daniel Day-Lewis`],
      videoLink: `http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4`,
    }, {
      backgroundColor: `#9B7E61`,
      backgroundImage: `https://htmlacademy-react-2.appspot.com/wtw/static/film/background/War_of_the_Worlds.jpg`,
      description: `As Earth is invaded by alien tripod fighting machines, one family fights for survival.`,
      director: `Steven Spielberg`,
      genre: `Adventure`,
      id: 2,
      isFavorite: true,
      name: `War of the Worlds`,
      posterImage: `https://htmlacademy-react-2.appspot.com/wtw/static/film/poster/War_of_the_Worlds.jpg`,
      previewImage: `https://htmlacademy-react-2.appspot.com/wtw/static/film/preview/war-of-the-worlds.jpg`,
      previewVideoLink: `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
      rating: 9.3,
      released: 2005,
      runTime: 116,
      scoresCount: 386834,
      starring: [`Tom Cruise`, `Dakota Fanning`, `Tim Robbins`],
      videoLink: `http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4`,
    }]);
  });
});
